### ISSUE TITLE
elmr config logout fails

### ISSUE THREAD

**Issue by ddriddle** [techservicesillinois/elmr#2]
If I go to `http://localhost/auth/elmr/config` then press logout (`http://localhost/auth/elmr/session?mode=logout`) I receive the following error in the browser:

```
HTTP Status 500 – Internal Server Error

Type Exception Report

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

java.lang.NullPointerException
	edu.illinois.techservices.elmr.servlets.SessionServlet.sessionDestroyed(SessionServlet.java:139)
	edu.illinois.techservices.elmr.servlets.SessionServlet.service(SessionServlet.java:41)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)

Note The full stack trace of the root cause is available in the server logs.
Apache Tomcat/9.0.11
```

**Comment by argherna** [comment]
See referenced commit above. This is ready to be pulled and tested again.

**Comment by ddriddle** [comment]
Logout now works as expected in the browser, but one of the tests that I wrote before this change is now failing. Specifically, if I preform a curl against elmr logout without a cookie I receive a 302, before I received a 500. Not sure what you think the correct behavior should be in this case. Maybe a 400 or a 401? Though I can also see the point of just redirecting to shib to make sure the shib cookies are killed off.

```
$ curl -I  http://127.0.0.1/auth/elmr/session?mode=logout
HTTP/1.1 302 302
Server: nginx/1.14.0
Date: Wed, 31 Oct 2018 20:51:01 GMT
Connection: keep-alive
Location: http://127.0.0.1/auth/Shibboleth.sso/Logout
```

**Comment by argherna** [comment]
The 302 status is what should have been happening all along. The 500 status with this test was a manifestation of the error that 93a5baa addresses; it was the unexpected result. If you change your test to assert the 302 status we can close this issue.

**Comment by ddriddle** [comment]
Done! Thanks.

**Comment by ddriddle** [comment]
Done. Thank!
