### ISSUE TITLE
HTTP Status 400 – Bad Request

### ISSUE THREAD

**Issue by yoonlees** [techservicesillinois/elmr#5]
We found that elmrsample fails after redirecting to /auth/elmr/session with following error message:

```
HTTP Status 400 – Bad Request

Type Status Report

Message Failed to find a request attribute named Shib_Session_ID. Please check your web server configuration.

Description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
Apache Tomcat/9.0.11
```

**Comment by ddriddle** [comment]
@argherna to debug this it would be great if `elmr` had a debug page that would print out the environment. Naturally, we would disable this page in production.

**Comment by argherna** [comment]
@ddriddle, great idea and we'll add that as an enhancement.

To get this going now, you will need to add the Shib_Session_ID as a JkEnvVar in the Apache configuration for elmrsample. This will send it across to /elmr/auth/session.

**Comment by argherna** [comment]
Reminder, to be able to use `/auth/elmr/config` you will have to set `edu.illinois.techservices.elmr.servlets.ApacheConfig` as a [system property](https://github.com/techservicesillinois/elmr/tree/develop#setting-system-properties-in-binsetenvsh-or-the-command-line) on the command line or [context parameter](https://github.com/techservicesillinois/elmr/tree/develop#setting-context-parameters-in-confcontextxml) in `elmr/conf/context.xml`.

**Comment by argherna** [comment]
And by the way, if `Shib_Session_ID` is not found in the environment this is the behavior elmr should respond with a 400 bad request status. This is expected. It makes my suspicion that Apache is not configured to pass this attribute as an environment variable to elmr more plausible to me.

**Comment by ddriddle** [comment]
@argherna We did set the `JkEnvVar` for `Shib_Session_ID` in the apache container:
```
httpd/root/etc/httpd/conf.d/mod_jk.conf:JkEnvVar Shib_Session_ID
```
We are able to access `/auth/elmr/config`. When I try accessing `/auth/elmr/config` locally using `docker-compose up -d` I see three vars: `displayName`, `eppn`, and `persistent-id`. Not sure what `persistent-id`is or why it is showing up.

I do not recall the exact details of what happened when we tried accessing `/auth/elmr/config` in AWS. Maybe @yoonlees does. Either way If you have time please join @yoonlees to debug this issue with him in a working session.

**Comment by argherna** [comment]
@kwessel suggested that we run a script that dumps the environment in the httpd container. I'm having @yoonlees take the script that's in master of illinois-shibboleth-sp-img and do just that. If `Shib_Session_ID` is there, then there's additional debugging in elmr to do.

**Comment by yoonlees** [comment]
Changing form Shib_Session_ID to Shib-Session-ID fixed the issue.
